version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: atiba-10
      MYSQL_DATABASE: ProWebb
      MYSQL_USER: root
      MYSQL_PASSWORD: atiba-10
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data_container:/var/lib/mysql
  api:
    depends_on:
        - db
    image: prowebbcore.api
    ports:
        - 8080:80
    build:
      context: ./ProWebbCore
      dockerfile: Dockerfile
volumes:
  db_data_container: {}