version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: atiba-10
      MYSQL_DATABASE: ProWebb
      MYSQL_USER: root
      MYSQL_PASSWORD: atiba-10
    ports:
      - 3307:3307
    restart: always
    volumes:
      - db_data_container:/var/lib/mysql
  api:
    depends_on:
        - db
    image: prowebbcore.api
    ports:
        - 8080:80
    build:
      context: ./ProWebbCore
      dockerfile: Dockerfile
  client:
    depends_on: 
      - api
    # image: node:13.12.0-alpine
    build: 
      context: ./Client
    volumes:
      - ./Client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
volumes:
  db_data_container: {}