version: '3.7'
services:
  db:
    image: mysql:latest
    environment:
      ROOT_PASSWORD: atiba-10
      DATABASE: ProWebb
      USER: root
      PASSWORD: atiba-10
    ports:
      - 3307:3306
    volumes:
      - db_data_container:/var/lib/mysql
  api:
    depends_on:
        - db
    image: prowebbcore.api
    ports:
        - 4001:80
    build:
      context: ./ProWebbCore
      dockerfile: Dockerfile
volumes:
  db_data_container: {}