version: '3.7'
services:
  # Note that this 'db' becomes the service name. 'localhost' will not work as the service name in prod.
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: atiba-10
      MYSQL_DATABASE: ProWebb
      MYSQL_USER: root
      MYSQL_PASSWORD: atiba-10
    ports:
      - 3307:3306
    restart: always
    volumes:
      - db_data_container:/var/lib/mysql
  api:
    depends_on:
        - db
    image: prowebbcore.api
    environment:
      # AWS_ACCESS_KEY_ID: ${HOST_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${HOST_AWS_SECRET_ACCESS_KEY}
    ports:
        - 8081:80
    build:
      context: ./ProWebbCore
      dockerfile: Dockerfile
    volumes:
      - /.aws/*:/app/.aws/
  client:
    depends_on: 
      - api
    build: 
      context: ./Client
    volumes:
      - ./Client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
volumes:
  db_data_container: {}