version: "3.7"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: atiba-10
      MYSQL_DATABASE: ProWebb
      MYSQL_USER: root
      MYSQL_PASSWORD: atiba-10
    ports:
      - 3307:3306 # This currently (As of 6/26) can't connect to API anymore. Who knows why ¯\_(ツ)_/¯
    restart: always
    volumes:
      - db_data_container:/var/lib/mysql
  api:
    depends_on:
      - db
    image: api
    ports:
      - "8081:80"
    build:
      context: ./ProWebbCore
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
volumes:
  db_data_container: {}
