version: '3.7'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: atiba-10
    ports:
      - 3306:3306
    volumes:
      - db_data_container:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
  api:
    image: prowebbcore.api
    build:
      context: ./prowebbcore.api
      dockerfile: Dockerfile
volumes:
  db_data_container: {}